"""
Integration test: Full LLM-driven image → SQL → SQLRunner flow.

This test only runs when real LLM keys are available and CEDARPY_TEST_LLM_READY=1.
It verifies that the Chief Agent plans the steps (ImageAnalysisAgent → SQLAgent → SQLRunner),
SQL is generated by the LLM (SQLAgent), and SQL execution is performed by SQLRunner.

We do not mock anything per project rules; failures will surface with logs.
"""

import os
import io
import json
import re
import tempfile
import time
import pytest

from starlette.testclient import TestClient


def _reload_app_isolated_env():
    tmp = tempfile.mkdtemp(prefix="cedarpy_llm_img_flow_")
    # Isolate data and enable shell API for test-only endpoints/WS auth
    os.environ["CEDARPY_DATA_DIR"] = tmp
    os.environ.setdefault("CEDARPY_SHELL_API_ENABLED", "1")
    os.environ.setdefault("CEDARPY_SHELL_API_TOKEN", "testtoken")
    os.environ.setdefault("CEDARPY_TEST_MODE", "0")  # real mode
    # Indicate readiness to run LLM tests (guard below will check keys as well)
    os.environ.setdefault("CEDARPY_TEST_LLM_READY", "1")

    import sys as _sys
    import importlib
    repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
    if repo_root not in _sys.path:
        _sys.path.insert(0, repo_root)
    import main  # noqa: F401
    importlib.reload(main)
    return main, tmp


def _create_project(client: TestClient, title: str | None = None) -> int:
    if not title:
        title = "LLM Image Flow"
    r = client.post("/projects/create", data={"title": title})
    assert r.status_code in (200, 303), f"create project failed: {r.status_code} {r.text}"
    home = client.get("/")
    assert home.status_code == 200
    m = re.search(r"/project/(\d+)", home.text)
    assert m, "project id not found"
    return int(m.group(1))


def _resolve_main_branch_id(client: TestClient, pid: int) -> int:
    token_q = "?token=testtoken"
    with client.websocket_connect(f"/ws/sql/{pid}{token_q}") as ws:
        ws.send_text(json.dumps({"sql": f"SELECT id FROM branches WHERE name='Main' AND project_id = {pid}"}))
        out = json.loads(ws.receive_text()); assert out.get("ok") is True
        return int(out.get("rows")[0][0])


def _last_file_row(client: TestClient, pid: int) -> dict:
    token_q = "?token=testtoken"
    with client.websocket_connect(f"/ws/sql/{pid}{token_q}") as ws:
        ws.send_text(json.dumps({"sql": "SELECT id, filename, display_name, file_type, mime_type, size_bytes FROM files ORDER BY id DESC LIMIT 1"}))
        out = json.loads(ws.receive_text()); assert out.get("ok") is True
        cols = out.get("columns"); row = out.get("rows")[0]
        return {cols[i]: row[i] for i in range(len(cols))}


@pytest.mark.timeout(600)
def test_llm_image_sql_flow_end_to_end():
    # Require real keys and readiness
    has_keys = bool(os.getenv("OPENAI_API_KEY") or os.getenv("CEDARPY_OPENAI_API_KEY"))
    if not has_keys or os.getenv("CEDARPY_TEST_LLM_READY") != "1":
        pytest.skip("LLM not reachable or keys missing; skipping LLM image→SQL flow test")

    main, tmp = _reload_app_isolated_env()
    try:
        with TestClient(main.app) as client:
            pid = _create_project(client)
            bid = _resolve_main_branch_id(client, pid)

            # Upload a small PNG (1x1) — sufficient to trigger ImageAnalysisAgent
            png_bytes = (
                b"\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x01\x00\x00\x00\x01"
                b"\x08\x02\x00\x00\x00\x90wS\xde\x00\x00\x00\x0cIDATx\x9cc``\x00\x00\x00\x04\x00\x01"
                b"\x0b\xe7\x02\x9a\x00\x00\x00\x00IEND\xaeB`\x82"
            )
            files = {"file": ("tiny.png", io.BytesIO(png_bytes), "image/png")}
            r = client.post(f"/project/{pid}/files/upload?branch_id={bid}", files=files, follow_redirects=False)
            assert r.status_code in (200, 303), f"upload failed: {r.status_code} {r.text}"

            # Start a chat asking for full pipeline and storage over WebSocket (single transport)
            prompt = (
                "Analyze the most recently uploaded image and extract structured JSON. "
                "Then generate SQL to create any needed tables and insert the analysis into the database, "
                "and execute that SQL. Report what you stored."
            )

            # Connect to orchestrator WS and send the message
            events = []
            with client.websocket_connect(f"/ws/chat/{pid}") as ws:
                # Send initial message
                ws.send_json({
                    "type": "message",
                    "content": prompt,
                    "branch_id": bid
                })
                t0 = time.time()
                found_image = found_sqlagent = found_sqlrunner = False
                # Read events up to 5 minutes
                while time.time() - t0 < 300:
                    msg = ws.receive_json()
                    events.append(msg)
                    t = (msg.get("type") or "").lower()
                    txt = (msg.get("text") or msg.get("content") or "").lower()
                    agent_name = (msg.get("agent_name") or "").lower()
                    if t == "agent_result":
                        if "image analysis" in (agent_name or txt):
                            found_image = True
                        if ("sql agent" in (agent_name or "")) or ("generated sql" in txt):
                            found_sqlagent = True
                        if ("sql runner" in (agent_name or "")) or ("sql execution report" in txt) or ("executed sql" in txt):
                            found_sqlrunner = True
                    if found_image and found_sqlagent and found_sqlrunner:
                        break

            assert found_image, "ImageAnalysisAgent evidence not found in streaming events"
            assert found_sqlagent, "SQLAgent evidence not found in streaming events"
            assert found_sqlrunner, "SQLRunner evidence not found in streaming events"

            # Verify at least one table exists from the executed SQL
            token_q = "?token=testtoken"
            with client.websocket_connect(f"/ws/sql/{pid}{token_q}") as ws:
                ws.send_text(json.dumps({"sql": "SELECT name FROM sqlite_master WHERE type='table'"}))
                out = json.loads(ws.receive_text()); assert out.get("ok") is True
                tables = [row[0] for row in (out.get("rows") or [])]
                assert len(tables) >= 1, "No tables found after SQLRunner execution"

            assert found_image, "ImageAnalysisAgent evidence not found in thread messages"
            assert found_sqlagent, "SQLAgent evidence not found in thread messages"
            assert found_sqlrunner, "SQLRunner evidence not found in thread messages"

            # Verify at least one table got created by the executed SQL
            with client.websocket_connect(f"/ws/sql/{pid}{token_q}") as ws:
                ws.send_text(json.dumps({"sql": "SELECT name FROM sqlite_master WHERE type='table'"}))
                out = json.loads(ws.receive_text()); assert out.get("ok") is True
                tables = [row[0] for row in (out.get("rows") or [])]
                assert len(tables) >= 1, "No tables found after SQLRunner execution"

    finally:
        try:
            import shutil; shutil.rmtree(tmp, ignore_errors=True)
        except Exception:
            pass
