name: CI

on:
  push:
  pull_request:

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dev and app dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          python -m pip install playwright
          python -m playwright install --with-deps chromium

      - name: Ruff (lint)
        run: ruff check .

      - name: Compile all (syntax check)
        run: python -m compileall -q .

      - name: Pytest (full)
        env:
          PYTHONPATH: .
          # Pass OpenAI key from repo or org secrets if available
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          CEDARPY_OPENAI_API_KEY: ${{ secrets.CEDARPY_OPENAI_API_KEY }}
        run: pytest -q
