name: macOS DMG (release)

on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt
          if [ -f packaging/requirements-macos.txt ]; then
            python -m pip install -r packaging/requirements-macos.txt
          fi
      - name: Build DMG (Qt)
        env:
          # Ensure gating script can use gh without prompting
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Require CI workflow name 'CI' to have passed; set CEDARPY_CI_WORKFLOW to 'CI' (default)
          CEDARPY_CI_WORKFLOW: CI
        run: |
          bash packaging/build_qt_dmg.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CedarPy.dmg
          path: packaging/dist-qt/CedarPy-qt.dmg

  release:
    needs: build
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: CedarPy.dmg
          path: dist
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/CedarPy-qt.dmg
          overwrite: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
