name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt
          python -m playwright install --with-deps chromium
      - name: Run tests (unit subset)
        env:
          CEDARPY_TEST_MODE: "1"
          PYTHONPATH: .
        run: |
          # Run a stable subset on ubuntu (exclude playwright/qt/ws-heavy tests; those run in main CI on proper runners)
          pytest -q -k "not playwright and not ws and not websockets and not qt" --maxfail=1 --disable-warnings --cache-clear
