name: tests

# Note: This is a quick subset runner. It does NOT replace the main CI.
# POLICY: No LLM stubs here either; use real keys from Secrets if present.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt
          python -m playwright install --with-deps chromium
      - name: Run tests (unit subset)
        env:
          PYTHONPATH: .
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          CEDARPY_OPENAI_API_KEY: ${{ secrets.CEDARPY_OPENAI_API_KEY }}
          CEDARPY_TEST_LLM_READY: "1"
          CEDARPY_DATA_DIR: ${{ runner.temp }}/CedarPyData  # ensure writable registry/files on CI runners
          CEDARPY_DATABASE_URL: sqlite:///${{ runner.temp }}/CedarPyData/cedarpy-registry.db
        run: |
          # Ensure data dir exists explicitly (defensive)
          mkdir -p "$RUNNER_TEMP/CedarPyData"
          # Run a stable subset on ubuntu (exclude playwright/qt/ws-heavy tests; those run in main CI on proper runners)
          # Do NOT cut tests in main CI. This is only a subset for quick feedback.
          pytest -q -k "not playwright and not ws and not websockets and not qt" --maxfail=1 --disable-warnings --cache-clear
